trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Instalar Node.js"

  - script: |
      npm install
    displayName: "Instalar dependências"

  - script: |
      npm run build
    displayName: "Compilar o projeto"

  - script: |
      npm test
    displayName: "Executar testes"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/test-results.xml"
      testRunTitle: "Resultados dos testes"
    condition: succeededOrFailed()

  - task: CopyFiles@2
    inputs:
      contents: "dist/**"
      targetFolder: "$(Build.ArtifactStagingDirectory)"
    displayName: "Preparar artefatos para publicação"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
    displayName: "Publicar artefatos"
